env:
    global:
        - CC_TEST_REPORTER_ID=ee9ab3556af050ae165142baf06d871cc6b26ab2d2a9afcc9e5012f5e0e48928
language: php
php:
    - 7.2
    - 7.3
script: phpunit --coverage-clover clover.xml
before_script:
    - cp .env.example .env
    - composer install --no-interaction
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
after_script:
    - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
